name: CI

on: [push, pull_request]

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black ruff

    - name: Run Black
      run: |
        black --check .

    - name: Run Ruff
      run: |
        ruff .

    - name: Run Tests
      run: |
        python run_tests.py
